name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'docusaurus.config.js'
      - 'sidebars.js'
      - 'i18n/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run build

    - name: Move build output to /en
      run: |
        mkdir -p build-temp
        cp -r build/* build-temp/
        mkdir -p build/en
        cp -r build-temp/* build/en/
        rm -rf build-temp

    - name: Add .nojekyll and CNAME (optional)
      run: |
        touch ./build/.nojekyll
        echo 'hoseinalizadeh1373.github.io' > ./build/CNAME

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        
